version: "3"
services:
  server-1:
    image: nginx
    container_name: server_1
    volumes:
      - ./server-1:/usr/share/nginx/html
    ports:
      - 7000:80
  server-2:
    image: nginx
    container_name: server_2
    volumes:
      - ./server-2:/usr/share/nginx/html
    ports:
      - 7001:80
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - server-1
      - server-2
